-- MySQL Script generated by MySQL Workbench
-- Mon Jan  4 22:03:08 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema g04
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema g04
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `g04` DEFAULT CHARACTER SET utf8 ;
USE `g04` ;

-- -----------------------------------------------------
-- Table `g04`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `g04`.`users` (
  `user_id` INT(32) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(16) CHARACTER SET 'armscii8' NOT NULL,
  `email` VARCHAR(255) NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `userID_UNIQUE` (`user_id` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `g04`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `g04`.`categories` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`category_id`));


-- -----------------------------------------------------
-- Table `g04`.`albums`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `g04`.`albums` (
  `album_id` INT NOT NULL AUTO_INCREMENT,
  `album_name` VARCHAR(45) NULL,
  `category_id` INT NULL,
  PRIMARY KEY (`album_id`),
  INDEX `category_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `category`
    FOREIGN KEY (`category_id`)
    REFERENCES `g04`.`categories` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `g04`.`authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `g04`.`authors` (
  `author_name` VARCHAR(45) NOT NULL,
  `author_id` INT NOT NULL AUTO_INCREMENT,
  UNIQUE INDEX `author_name_UNIQUE` (`author_name` ASC) VISIBLE,
  PRIMARY KEY (`author_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `g04`.`songs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `g04`.`songs` (
  `song_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `author_id` INT NULL,
  `length_sec` INT(32) NULL,
  `is_single` TINYINT NULL,
  `album_id` INT NULL,
  PRIMARY KEY (`song_id`),
  INDEX `album_idx` (`album_id` ASC) VISIBLE,
  INDEX `author_idx` (`author_id` ASC) VISIBLE,
  CONSTRAINT `album`
    FOREIGN KEY (`album_id`)
    REFERENCES `g04`.`albums` (`album_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `author`
    FOREIGN KEY (`author_id`)
    REFERENCES `g04`.`authors` (`author_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `g04`.`votes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `g04`.`votes` (
  `song_id` INT NULL,
  `user_id` INT NULL,
  `vote_id` INT NOT NULL AUTO_INCREMENT,
  INDEX `user_idx` (`user_id` ASC) VISIBLE,
  INDEX `song_idx` (`song_id` ASC) VISIBLE,
  PRIMARY KEY (`vote_id`),
  CONSTRAINT `user`
    FOREIGN KEY (`user_id`)
    REFERENCES `g04`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `song`
    FOREIGN KEY (`song_id`)
    REFERENCES `g04`.`songs` (`song_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
